using ClosedXML.Excel;
using ClosedXML.Excel.Drawings;
using Sidwell.Backend.Application.Contracts.Infrastructure;
using Sidwell.Backend.Application.Dtos;

namespace Sidwell.Backend.Infrastructure.Implementations.Reports;

public sealed class XlsxJournalReportRenderer : IJournalReportRenderer
{
    private static readonly XLColor BrandAccent = XLColor.FromHtml("#059669");
    private static readonly XLColor MutedGray = XLColor.FromHtml("#6B7280");

    public bool CanRender(ReportFormat format) => format == ReportFormat.Xlsx;

    public Task<JournalReportFile> RenderAsync(JournalReportContext context, ReportFormat format, CancellationToken ct = default)
    {
        if (!CanRender(format))
            throw new NotSupportedException($"{nameof(XlsxJournalReportRenderer)} only supports {nameof(ReportFormat.Xlsx)}.");

        using XLWorkbook workbook = new();
        BuildNoteSheet(workbook, context);
        if (context.TickerAnalysis is not null)
            BuildAnalysisSheets(workbook, context.TickerAnalysis);

        if (context.IncludeAttachments)
        {
            List<string> unsupported = [];

            foreach (TickerNoteAttachmentDto attachment in context.Note.Attachments)
            {
                byte[] bytes;
                try { bytes = Convert.FromBase64String(attachment.DataBase64); }
                catch { unsupported.Add($"{attachment.Name} — corrupted attachment data"); continue; }

                try
                {
                    if (IsXlsxMimeType(attachment.MimeType))
                        AppendXlsxSheets(workbook, bytes, attachment.Name);
                    else if (TryGetPictureFormat(attachment.MimeType, out XLPictureFormat pictureFormat))
                        AppendImageSheet(workbook, bytes, pictureFormat, attachment.Name);
                    else
                        unsupported.Add($"{attachment.Name} ({attachment.MimeType})");
                }
                catch
                {
                    unsupported.Add($"{attachment.Name} — could not be embedded (corrupted or unsupported variant)");
                }
            }

            if (unsupported.Count > 0)
                AddUnsupportedSheet(workbook, unsupported);
        }

        using MemoryStream stream = new();
        workbook.SaveAs(stream);

        string fileName = $"{context.Symbol}-{ReportFileNaming.Slugify(context.Note.Title)}.xlsx";

        return Task.FromResult(new JournalReportFile(
            stream.ToArray(), fileName, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"));
    }

    private static void BuildNoteSheet(XLWorkbook workbook, JournalReportContext context)
    {
        IXLWorksheet ws = workbook.Worksheets.Add("Note");
        ws.Column(1).Width = 100;

        ws.Cell(1, 1).Value = context.Symbol;
        ws.Cell(1, 1).Style.Font.FontSize = 22;
        ws.Cell(1, 1).Style.Font.Bold = true;
        ws.Cell(1, 1).Style.Font.FontColor = BrandAccent;

        ws.Cell(2, 1).Value = context.Note.Title;
        ws.Cell(2, 1).Style.Font.FontSize = 14;
        ws.Cell(2, 1).Style.Font.Bold = true;

        ws.Cell(3, 1).Value =
            $"Generated by {context.AuthorName} · {DateTimeOffset.Now:dd MMM yyyy, HH:mm} · " +
            $"Note created {context.Note.CreatedAt:dd MMM yyyy}";
        ws.Cell(3, 1).Style.Font.Italic = true;
        ws.Cell(3, 1).Style.Font.FontColor = MutedGray;
        ws.Cell(3, 1).Style.Font.FontSize = 9;

        int row = 5;
        bool multi = context.Note.Sections.Count(s => !string.IsNullOrWhiteSpace(s.Content)) > 1;
        int index = 1;

        foreach (TickerNoteSectionDto s in context.Note.Sections)
        {
            if (string.IsNullOrWhiteSpace(s.Content)) continue;

            if (multi)
            {
                IXLCell heading = ws.Cell(row, 1);
                heading.Value = $"Section {index}";
                heading.Style.Font.Bold = true;
                heading.Style.Font.FontColor = BrandAccent;
                row++;
                index++;
            }

            IXLCell body = ws.Cell(row, 1);
            body.Value = s.Content;
            body.Style.Alignment.WrapText = true;
            body.Style.Alignment.Vertical = XLAlignmentVerticalValues.Top;
            row += 2;
        }

        if (context.IncludeAttachments && context.Note.Attachments.Count > 0)
        {
            row++;
            IXLCell heading = ws.Cell(row, 1);
            heading.Value = "Attachments";
            heading.Style.Font.Bold = true;
            heading.Style.Font.FontColor = BrandAccent;
            row++;

            foreach (TickerNoteAttachmentDto a in context.Note.Attachments)
            {
                ws.Cell(row, 1).Value = $"• {a.Name} ({a.MimeType})";
                row++;
            }
        }
    }

    private static void BuildAnalysisSheets(XLWorkbook workbook, TickerDetail detail)
    {
        WriteFactsSheet(workbook, "Snapshot", ReportSectionData.BuildHeaderFacts(detail));
        WriteFactsSheet(workbook, "Composite", ReportSectionData.BuildCompositeFacts(detail.Composite));
        WriteFactsSheet(workbook, "Key stats", ReportSectionData.BuildKeyStatsFacts(detail.KeyStats));
        WriteFactsSheet(workbook, "Dividends", ReportSectionData.BuildDividendFacts(detail.Dividends));

        if (detail.Holding is not null)
            WriteFactsSheet(workbook, "Holding", ReportSectionData.BuildHoldingFacts(detail.Holding));

        WriteTableSheet(workbook, "Algorithms", ReportSectionData.BuildAlgorithmsTable(detail.Algorithms));

        if (detail.GatedAlgos.Count > 0)
            WriteTableSheet(workbook, "Algos gated", ReportSectionData.BuildGatedAlgosTable(detail.GatedAlgos));

        if (detail.Fundamentals.Count > 0)
            WriteTableSheet(workbook, "Fundamentals", ReportSectionData.BuildFundamentalsTable(detail.Fundamentals));

        if (detail.Price.History.Count > 0)
            WriteTableSheet(workbook, "Price history", ReportSectionData.BuildPriceHistoryTable(detail.Price.History));

        if (detail.News.Count > 0)
            WriteTableSheet(workbook, "News", ReportSectionData.BuildNewsTable(detail.News));
    }

    private static void WriteFactsSheet(XLWorkbook workbook, string sheetName, IReadOnlyList<(string Label, string Value)> facts)
    {
        if (facts.Count == 0) return;

        IXLWorksheet ws = workbook.Worksheets.Add(MakeUniqueSheetName(workbook, sheetName));
        ws.Column(1).Width = 30;
        ws.Column(2).Width = 60;

        for (int i = 0; i < facts.Count; i++)
        {
            IXLCell labelCell = ws.Cell(i + 1, 1);
            labelCell.Value = facts[i].Label;
            labelCell.Style.Font.Bold = true;
            labelCell.Style.Font.FontColor = MutedGray;

            ws.Cell(i + 1, 2).Value = facts[i].Value;
        }
    }

    private static void WriteTableSheet(XLWorkbook workbook, string sheetName, ReportTable data)
    {
        IXLWorksheet ws = workbook.Worksheets.Add(MakeUniqueSheetName(workbook, sheetName));

        for (int c = 0; c < data.Headers.Count; c++)
        {
            IXLCell headerCell = ws.Cell(1, c + 1);
            headerCell.Value = data.Headers[c];
            headerCell.Style.Font.Bold = true;
            headerCell.Style.Font.FontColor = XLColor.White;
            headerCell.Style.Fill.BackgroundColor = BrandAccent;
        }

        for (int r = 0; r < data.Rows.Count; r++)
        {
            IReadOnlyList<string> row = data.Rows[r];
            for (int c = 0; c < data.Headers.Count && c < row.Count; c++)
                ws.Cell(r + 2, c + 1).Value = row[c];
        }

        ws.Columns().AdjustToContents();
    }

    private static bool IsXlsxMimeType(string mimeType) =>
        mimeType is "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" or "application/vnd.ms-excel";

    private static bool TryGetPictureFormat(string mimeType, out XLPictureFormat format)
    {
        switch (mimeType.ToLowerInvariant())
        {
            case "image/png": format = XLPictureFormat.Png; return true;
            case "image/jpeg":
            case "image/jpg": format = XLPictureFormat.Jpeg; return true;
            case "image/gif": format = XLPictureFormat.Gif; return true;
            case "image/bmp": format = XLPictureFormat.Bmp; return true;
            case "image/tiff": format = XLPictureFormat.Tiff; return true;
            default: format = default; return false;
        }
    }

    private static void AppendXlsxSheets(XLWorkbook destination, byte[] bytes, string attachmentName)
    {
        using MemoryStream stream = new(bytes);
        using XLWorkbook source = new(stream);

        foreach (IXLWorksheet sourceSheet in source.Worksheets)
        {
            string name = MakeUniqueSheetName(destination, $"{attachmentName}-{sourceSheet.Name}");
            sourceSheet.CopyTo(destination, name);
        }
    }

    private static void AppendImageSheet(XLWorkbook destination, byte[] bytes, XLPictureFormat format, string attachmentName)
    {
        string name = MakeUniqueSheetName(destination, attachmentName);
        IXLWorksheet ws = destination.Worksheets.Add(name);

        using MemoryStream imageStream = new(bytes);
        ws.AddPicture(imageStream, format).MoveTo(ws.Cell(1, 1));
    }

    private static void AddUnsupportedSheet(XLWorkbook workbook, List<string> items)
    {
        IXLWorksheet ws = workbook.Worksheets.Add(MakeUniqueSheetName(workbook, "Not included"));
        ws.Column(1).Width = 90;

        ws.Cell(1, 1).Value = "The following attachments could not be embedded — download them individually from the note in the app:";
        ws.Cell(1, 1).Style.Font.Italic = true;
        ws.Cell(1, 1).Style.Font.FontColor = MutedGray;

        int row = 3;
        foreach (string item in items)
        {
            ws.Cell(row, 1).Value = item;
            row++;
        }
    }

    private static string MakeUniqueSheetName(XLWorkbook workbook, string desired)
    {
        string sanitized = SanitizeSheetName(desired);
        string candidate = sanitized;
        int suffix = 2;

        while (workbook.Worksheets.Any(w => string.Equals(w.Name, candidate, StringComparison.OrdinalIgnoreCase)))
        {
            string suffixText = $" ({suffix})";
            candidate = sanitized.Length + suffixText.Length > 31
                ? sanitized[..(31 - suffixText.Length)] + suffixText
                : sanitized + suffixText;
            suffix++;
        }

        return candidate;
    }

    private static string SanitizeSheetName(string name)
    {
        char[] invalid = ['\\', '/', '?', '*', '[', ']', ':'];
        char[] cleaned = name.Select(c => invalid.Contains(c) ? '-' : c).ToArray();
        string result = new(cleaned);

        return result.Length > 31 ? result[..31] : result;
    }
}
